### ISSUE TITLE
Attribute error when attempting to use a kanji font

### ISSUE THREAD

**Issue by hierophect** [adafruit/Adafruit_CircuitPython_Display_Text#41]
I'm attempting to load a 16 point kanji font into Circuitpython (attached)
[kanji16.bdf.zip](https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/files/4588341/kanji16.bdf.zip)
, but I'm encountering the following error:
```
Traceback (most recent call last):
  File "code.py", line 78, in <module>
  File "adafruit_display_text/label.py", line 90, in __init__
  File "adafruit_display_text/label.py", line 98, in _update_text
AttributeError: 'NoneType' object has no attribute 'height'
```

I'm not sure if this is related to the font itself - is it possible for a .bdf to not include the correct glyph properties for this library? It loads correctly in FontForge.

**Comment by hierophect** [comment]
Well, after some considerable debugging time it seems that this was caused by missing metadata in the .bdf files I tried, which is included by otf2bdf but seems to be omitted by most raw .bdf fonts found online. While it would be interesting to know what causes this and whether there's an easy fix that makes these fonts usable, it's probably not worth having an issue to fix the fact that some random files I found online have different metadata. Closing.
